version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64

    goarm:
      - 6
      - 7

    ldflags:
      - -s -w
      - -X github.com/geaaru/entities/cmd.BuildTime={{.Date}}
      - -X github.com/geaaru/entities/cmd.BuildCommit={{.Commit}}
      - -X github.com/geaaru/entities/cmd.BuildGoVersion={{ .Env.GOVERSION }}

archives:
  - format: binary
    name_template: entities-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Tag }}-source'
checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}-checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^scripts:'
      - '^contrib'
      - '^.github'
      - '^.lxd-compose.yml'
